import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Nunito, Nunito_Sans } from "next/font/google";
import "./globals.css";

const headerFont = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const bodyFont = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headerFont.variable} ${bodyFont.variable} antialiased  mx-auto `}
      >
        <Navbar />
        <div className="bg-off-white">{children}</div>
      </body>
    </html>
  );
}
